apiVersion: v1
kind: ConfigMap
metadata:
  name: villain-config
data:
  quarkus.datasource.username: "super"
  quarkus.hibernate-orm.schema-management.strategy: "create"
  quarkus.otel.exporter.otlp.traces.endpoint: "http://alloy.monitoring:4317"
