apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "quarkus-workshop-stat"
    version: "01"
    group: "super-heroes"
  name: "quarkus-workshop-stat"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "quarkus-workshop-stat"
      version: "01"
      group: "super-heroes"
  template:
    metadata:
      labels:
        app: "quarkus-workshop-stat"
        version: "01"
        group: "super-heroes"
    spec:
      containers:
      - image: "esara/quarkus-workshop-statistic"
        imagePullPolicy: "IfNotPresent"
        name: "quarkus-workshop-stat"
        ports:
        - containerPort: 8085
        env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: QUARKUS_HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: stat-config
              key: port
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            secretKeyRef:
              name: kafka-connection-secret
              key: clusterEndpointScramPublic
        - name: KAFKA_SECURITY_PROTOCOL
          value: SASL_SSL
        - name: KAFKA_SASL_MECHANISM
          value: SCRAM-SHA-512
        - name: KAFKA_SASL_JAAS_CONFIG
          value: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME:admin}" password="${KAFKA_PASSWORD:quarkus}";
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "quarkus-workshop-stat"
    version: "01"
    group: "super-heroes"
  name: "quarkus-workshop-stat"
spec:
  ports:
    - name: "http"
      port: 8085
  selector:
    app: "quarkus-workshop-stat"
    version: "01"
    group: "super-heroes"
  type: "NodePort"
