apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-locations-config
data:
  quarkus.datasource.jdbc.url: "jdbc:postgresql://super-dbs:5432/locations"
  quarkus.datasource.username: "superlocation"
  quarkus.hibernate-orm.schema-management.strategy: "create"
  quarkus.otel.exporter.otlp.traces.endpoint: "http://alloy.monitoring:4317"
