apiVersion: v1
kind: ConfigMap
metadata:
  name: stat-config
data:
  kafka.bootstrap.servers: "PLAINTEXT://super-heroes-kafka-brokers:9092"
  mp.messaging.connector.smallrye-kafka.apicurio.registry.url: "http://apicurio:8080/apis/registry/v2"
  quarkus.otel.exporter.otlp.traces.endpoint: "http://alloy.monitoring:4317"
