apiVersion: v1
kind: ConfigMap
metadata:
  name: hero-config
data:
  quarkus.datasource.reactive.url: "postgresql://super-dbs:5432/hero"
  quarkus.datasource.reactive.postgresql.ssl-mode: "require"
  quarkus.datasource.reactive.trust-all: "true"
  quarkus.hibernate-orm.schema-management.strategy: "create"
  quarkus.otel.exporter.otlp.traces.endpoint: "http://alloy.monitoring:4317"
