apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: quarkus-super-heroes-monitor
  name: quarkus-super-heroes
spec:
  endpoints:
    - interval: 30s
      targetPort: 8080
      path: /q/metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: quarkus
